set PATH=%PATH%;D:\WATCOM\BINNT64;D:\WATCOM\BINNT
set INCLUDE=%INCLUDE%;D:\WATCOM\H;D:\WATCOM\H\NT;D:\WATCOM\H\NT\DIRECTX;D:\WATCOM\H\NT\DDK
set WATCOM=D:\WATCOM
set EDPATH=D:\WATCOM\EDDAT
set WHTMLHELP=D:\WATCOM\BINNT\HELP
set WIPFC=D:\WATCOM\WIPFC
